/**
 * Tables authored by BracketX.
 *
 * Everything in `./auth.ts` is generated by the Better Auth CLI and must not be
 * hand-edited except for the deliberate adjustments documented there. This file
 * is ours.
 */
import { index, pgTable, text, timestamp, unique } from "drizzle-orm/pg-core";

import { organization, user } from "./auth";

export const project = pgTable(
  "project",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),

    /**
     * The owning workspace. `organization` *is* our workspace — there is no
     * separate workspace table (ARCHITECTURE.md §5).
     */
    organizationId: text("organization_id")
      .notNull()
      .references(() => organization.id, { onDelete: "cascade" }),

    name: text("name").notNull(),

    /**
     * Unique per organization, not globally. Two workspaces may both have a
     * project called `season-opener`; global uniqueness would leak one
     * customer's naming into another's namespace.
     *
     * Note this differs from `organization.slug`, which Better Auth enforces as
     * globally unique.
     */
    slug: text("slug").notNull(),

    /**
     * Nullable, and SET NULL rather than CASCADE on purpose: a project belongs
     * to the workspace, not to the person who created it. Deleting a user must
     * never delete their team's projects.
     */
    createdById: text("created_by_id").references(() => user.id, {
      onDelete: "set null",
    }),

    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (table) => [
    unique("project_organization_id_slug_unique").on(
      table.organizationId,
      table.slug,
    ),
    index("project_organization_id_idx").on(table.organizationId),
    /**
     * Postgres does not index foreign key columns automatically, and the
     * referencing side is what gets scanned when the referenced row goes away.
     * Without this, every user deletion sequentially scans `project` to apply
     * ON DELETE SET NULL. Cheap now; a lock-holding table scan later.
     */
    index("project_created_by_id_idx").on(table.createdById),
  ],
);

export type Project = typeof project.$inferSelect;
export type NewProject = typeof project.$inferInsert;
